stages:
  - test
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/your-repo/ornitools-backend

test:
  stage: test
  image: python:3.11
  script:
    - pip install poetry
    - poetry install
    - poetry run python manage.py test
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
