# Generated by Django 4.2.6 on 2024-11-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bird",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "given_name",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the bird's GPS data should be publicly visible.",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="bird_photos/"),
                ),
            ],
            options={
                "verbose_name": "Bird",
                "verbose_name_plural": "Birds",
            },
        ),
        migrations.CreateModel(
            name="GPSDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gps_tag_id", models.CharField(max_length=100, unique=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "GPSDevice",
                "verbose_name_plural": "GPSDevices",
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("scientific_name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "conservation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "Least Concern"),
                            ("NT", "Near Threatened"),
                            ("VU", "Vulnerable"),
                            ("EN", "Endangered"),
                            ("CR", "Critically Endangered"),
                            ("EW", "Extinct in the Wild"),
                            ("EX", "Extinct"),
                            ("DD", "Data Deficient"),
                            ("NE", "Not Evaluated"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
            },
        ),
        migrations.CreateModel(
            name="GPSPositionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="gps_position_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bird",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_file",
                        to="ornitools.bird",
                    ),
                ),
                (
                    "gps_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="ornitools.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPSPositionFile",
                "verbose_name_plural": "GPSPositionFiles",
                "unique_together": {("bird", "gps_device", "file")},
            },
        ),
        migrations.CreateModel(
            name="GPSPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "position_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="ornitools.gpspositionfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPSPosition",
                "verbose_name_plural": "GPSPosition",
            },
        ),
        migrations.AddField(
            model_name="bird",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="birds",
                to="ornitools.species",
            ),
        ),
    ]
