# Generated by Django 5.1.2 on 2024-11-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0002_remove_bird_age_remove_bird_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="gps_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bird",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_file",
                        to="ornitools.bird",
                    ),
                ),
                (
                    "gps_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="ornitools.gpsdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPSFile",
                "verbose_name_plural": "GPSFiles",
                "unique_together": {("bird", "gps_device", "file")},
            },
        ),
        migrations.AlterField(
            model_name="gpsposition",
            name="position_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="ornitools.gpsfile",
            ),
        ),
        migrations.DeleteModel(
            name="GPSPositionFile",
        ),
    ]
