# Generated by Django 5.1.2 on 2024-11-12 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0003_gpsfile_alter_gpsposition_position_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gpsposition",
            old_name="position_file",
            new_name="gps_file",
        ),
    ]
