# Generated by Django 5.1.2 on 2024-11-12 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0004_rename_position_file_gpsposition_gps_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bird",
            old_name="identifier",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="gpsdevice",
            old_name="gps_tag_id",
            new_name="name",
        ),
    ]
