# Generated by Django 5.1.2 on 2024-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0005_rename_identifier_bird_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="given_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="gpsposition",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "timestamp"),
                name="unique_gps_position",
            ),
        ),
    ]
