# Generated by Django 5.1.2 on 2024-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0006_alter_bird_given_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
