# Generated by Django 5.1.2 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ornitools", "0008_bird_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gpsposition",
            name="unique_gps_position",
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="U_bat_mV",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="acc_x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="acc_y",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="acc_z",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="altitude_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="bat_soc_pct",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="direction_deg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="hdop",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="mag_x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="mag_y",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="mag_z",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="satcount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="solar_I_mA",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="speed_km_h",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpsposition",
            name="temperature_C",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="gpsposition",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "timestamp", "altitude_m"),
                name="unique_gps_position",
            ),
        ),
    ]
